name: Test benchmark sites (every 30m)

on:
  schedule:
    - cron: "*/30 * * * *"

  workflow_dispatch:
    inputs:
      token:
        description: 'secret token'
        required: true

#concurrency: 
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
    - uses: actions/checkout@master
    
    - name: docker registry login
      run: echo "${{  secrets.DOCKER_CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io --username hoangweb --password-stdin
      
    - name: Run cron
      if: success()
      run: |
        docker run \
        -e JOB_NAME="scan_ddos" \
        ghcr.io/hoangweb/w2pddos:latest
